configured_endpoints: 3
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nordic-game-lab%2Flearnhub-sdk-c0d844334ca766d748794b8ff87c3a76f2a26775c5fc4251e7a489ab2f31ccb5.yml
